act_id: 2
attention_probs_dropout_prob: 0.1
decoder_hidden_size: 32
decoder_intermediate_size: 64
decoder_num_hidden_layers: 3
embedding_size: 32
fixed_pe: false
generator_temperature: 1.0
hidden_act: gelu
hidden_dropout_prob: 0.0
hidden_size: 256
initializer_range: 0.02
intermediate_size: 512
layer_norm_eps: 1.0e-12
max_position_embeddings: 513
num_attention_heads: 4
num_hidden_layers: 6
obs_id: 1
pad_id: 0
tie_weights: true
traj_id: 4
type_vocab_size: 3
unique_top_layers: true
unk_id: 3
vocab_size: 1024
